-- Tabla de visitas mejorada
CREATE TABLE IF NOT EXISTS visitas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_visita TIMESTAMPTZ DEFAULT NOW(),
    pagina TEXT DEFAULT 'index',
    tipo TEXT DEFAULT 'visita',
    
    -- Información del visitante
    ip_address TEXT,
    user_agent TEXT,
    dispositivo TEXT,
    navegador TEXT,
    sistema TEXT,
    
    -- Información adicional
    referrer TEXT,
    lenguaje TEXT,
    pantalla_resolucion TEXT,
    hora_local TEXT,
    fecha_local TEXT,
    
    -- UTM / Marketing
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    
    -- Sesión
    session_id TEXT,
    tiempo_sesion INTEGER DEFAULT 0
);

-- Habilitar Row Level Security
ALTER TABLE visitas ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow all inserts" ON visitas FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all selects" ON visitas FOR SELECT USING (true);
CREATE POLICY "Allow all updates" ON visitas FOR UPDATE USING (true);